version: '3.8'

services:
  users:
    build:
      context: ./users
      dockerfile: Dockerfile
    image: userdetails
    ports:
      - "8000:8000"
      - "8001:8001"
    depends_on:
      - db

  chatbot:
    build:
      context: ./chatbot
      dockerfile: Dockerfile
    image: chatbot
    ports:
      - "8002:8002"
    depends_on:
      - db

  summarize:
    build:
      context: ./summarize
      dockerfile: Dockerfile
    image: summarize
    ports:
      - "8003:8003"
    depends_on:
      - db

  db:
    image: mysql:latest
    environment:
       MYSQL_ROOT_PASSWORD: Eswar1310
       MYSQL_DATABASE: db
       MYSQL_USER: Eswar
       MYSQL_PASSWORD: Eswar1310
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
